package matcher

import "github.com/prometheus/client_golang/prometheus"

type Metric struct {
	OrdersMatched  prometheus.Counter
	TradesProduced prometheus.Counter
	MatchLatency   prometheus.Histogram
}

func NewMetric(reg *prometheus.Registry, namespace, serviceName string) *Metric {
	om := prometheus.NewCounter(prometheus.CounterOpts{
		Namespace:   namespace,
		Subsystem:   serviceName,
		Name:        "orders_matched_total",
		Help:        "total number of orders processed by the matching engine",
		ConstLabels: prometheus.Labels{},
	})

	if err := reg.Register(om); err != nil {
		panic(err)
	}

	tp := prometheus.NewCounter(prometheus.CounterOpts{
		Namespace:   namespace,
		Subsystem:   serviceName,
		Name:        "trades_produced_total",
		Help:        "total number of trades generated by the matching engine",
		ConstLabels: prometheus.Labels{},
	})

	if err := reg.Register(tp); err != nil {
		panic(err)
	}

	ml := prometheus.NewHistogram(prometheus.HistogramOpts{
		Namespace:                       namespace,
		Subsystem:                       serviceName,
		Name:                            "match_latency_seconds",
		Help:                            "time spent matching a single order in seconds",
		ConstLabels:                     prometheus.Labels{},
		Buckets:                         prometheus.DefBuckets,
		NativeHistogramBucketFactor:     0,
		NativeHistogramZeroThreshold:    0,
		NativeHistogramMaxBucketNumber:  0,
		NativeHistogramMinResetDuration: 0,
		NativeHistogramMaxZeroThreshold: 0,
		NativeHistogramMaxExemplars:     0,
		NativeHistogramExemplarTTL:      0,
	})

	if err := reg.Register(ml); err != nil {
		panic(err)
	}

	return &Metric{
		OrdersMatched:  om,
		TradesProduced: tp,
		MatchLatency:   ml,
	}
}
