{
 "title": "Redpanda101",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{ job }}" }
   ]
  },
  {
   "title": "Message Delay",
   "type": "timeseries",
   "description": "The time it takes for a message to go into Redpanda and then back to the consumer, based on the Kafka message timestamp.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(parham_learning_redpanda101_message_delay_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(parham_learning_redpanda101_message_delay_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(parham_learning_redpanda101_message_delay_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Database Insertion Time",
   "type": "timeseries",
   "description": "The time it takes for a record read from Redpanda to be written into Postgres",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(parham_learning_redpanda101_database_insertion_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(parham_learning_redpanda101_database_insertion_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(parham_learning_redpanda101_database_insertion_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}